### ISSUE TITLE
FP value 0.3

### ISSUE THREAD

**Issue by simaker** [ZwwWayne/mmMOT#10]
Hi ,
in your paper you wrote, that you discard all detections with a score below 0.3. Is this value a parameter? I can't find it in the Code

**Comment by ZwwWayne** [comment]
This value is set in the codebase of SECOND. Because usually, the test submission uses value 0.3 to filter low confident detections and works well, so I adopt it. We did not tune this.

**Comment by simaker** [comment]
okay thank you for your fast answer :)
