### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by zhangpur2** [ZwwWayne/mmMOT#12]
Hi, thanks for your great work:)
There's some problem with understanding the official code:
`curr_dets, add_num = add_miss_dets(`
`prev_dets,`
` dets,`
`iou_threshold=iou_threshold,`
`fix_threshold=fix_threshold)  # add missed dets`
`add_count += add_num`
` add_frame += int(add_num > 0)`

Why do we need the function of  `add_miss_dets`? Actually the program always end up at
` if len(index) == 0:`
` return dets, 0`

 inside the function, when dealing with pp_train_dets.pkl and pp_val_dets.pkl.

**Comment by ZwwWayne** [comment]
This function adds detected objects from previous frames into current frames. However, during our experiment, we find this trick does not help, so we do not use it in this release code.

**Comment by zhangpur2** [comment]
Thanks.
