### ISSUE TITLE
Visualization tool

### ISSUE THREAD

**Issue by dogyoonlee** [ZwwWayne/mmMOT#19]
Could you let me know how did you visualize your results on image and 3D space?
Is there any reference codes?

**Comment by ZwwWayne** [comment]
https://github.com/ZwwWayne/mmMOT/issues/6

**Comment by llllliu1** [comment]
> Could you let me know how did you visualize your results on image and 3D space?
> Is there any reference codes?

@dogyoonlee hi~ now do you have a demo code to solve the visualization?
