### ISSUE TITLE
time consuming?

### ISSUE THREAD

**Issue by AndyYuan96** [ZwwWayne/mmMOT#2]
Hi, I see your result in kitti, the time consuming is 0.01s , it's so excellent, I just wonder if you can me what gpu you are using?

**Comment by ZwwWayne** [comment]
The time is calculated on the v100 GPU card, and only calculates the time of model inference.
I just found the time should be about 0.01~0.02s, and 0.02s is more accurate after rounding, so I correct the information on the benchmark, thanks for your interest.

**Comment by ZwwWayne** [comment]
The issue is closed because the question seems to be answered, feel free to reopen it if you have any further questions.
