### ISSUE TITLE
nuScenes support and multiple cameras / radars support 

### ISSUE THREAD

**Issue by sergiev** [ZwwWayne/mmMOT#22]
Hey! Thanks for your work. Glad you've decided to use pytorch.
But looking through paper and code was not clear for me if there is any plans on utilizing the capabilities of 360 degree FOV systems like nuScenes dataset? Or maybe I've just missed the part where multiple cameras are implicit to be used. I'll be very glad for your clarification.

Also it's very interesting to know if there was any experiments with radar data.

**Comment by ZwwWayne** [comment]
Hi @sergiev ,
We have not tried the method on nuScenes either radar data since the paper is done when nuScenes only provide v1.0-mini. We will try it in the future.
