### ISSUE TITLE
RRC pre-trained model availability

### ISSUE THREAD

**Issue by dmatos2012** [ZwwWayne/mmMOT#23]
Hello, 

You provide 4 pre trained model for PointPillar. However, for RRC, I do not see the checkpoint: `ckpt_best.pth.tar` that we are supposed to load from the script in experiments/rrc_pfv_40e_subabs_dualadd_C/eval.sh  in  in your google drive, therefore it is not found when running the code for RRC detections.

Do we have to train it ourselves? Evaluation with PP has been without any issues.

**Comment by ZwwWayne** [comment]
Hi @dmatos2012 ,
The checkpoint using RRC is not provided. The script is for usage after users trained the model by themselves.
