### ISSUE TITLE
Score on Tracking Result

### ISSUE THREAD

**Issue by dmatos2012** [ZwwWayne/mmMOT#24]
Hello,
Again thanks for the great work. I noticed that in the evaluation results, the score is hardcoded to 0.90 in [data_util.py](https://github.com/ZwwWayne/mmMOT/blob/master/utils/data_util.py) on `writte_kitti_result` function. I attempted to obtain it by using `frames_det[i]['score'][j].item()` (line 115), but get key error. Is it possible to obtain the actual confidence score when writing result to text file?

This isnt a problem per se, as in kitti evaluation the tracking score is not used, but I would like to evaluate it on a different benchmark.

Thanks again.

**Comment by ZwwWayne** [comment]
Hi @dmatos2012 ,
As you can see from this [line](https://github.com/ZwwWayne/mmMOT/blob/master/tracking_model.py#L69). The score of each detection is passed out and used for matching for detections between two frames. But we did not pass it out for result submission. You can use it if you wish to utilize the scores.

**Comment by dmatos2012** [comment]
Thanks for the very prompt response!
