### ISSUE TITLE
what is the pp_train_dets.pkl?

### ISSUE THREAD

**Issue by woosual** [ZwwWayne/mmMOT#25]
Hi, when  I use the fusion moudles in ./experiments, I found there is no file named 'pp_train_dets.pkl' as the 'train_det' or 'val_det'. Could you please tell me how can I solve this problem?  Thank you.

**Comment by FrankCAN** [comment]
You can check the readme carefully, there is a google drive link for all the necessary files.

**Comment by llllliu1** [comment]
> You can check the readme carefully, there is a google drive link for all the necessary files.

hey， Why can't I open this page？
