### ISSUE TITLE
how to predict via your model(pretrained or trained)

### ISSUE THREAD

**Issue by ayowei314** [ZwwWayne/mmMOT#28]
i' am a beginner in deep-learning, where to input （e.g.any two pictures from kitti, including point cloud information） and get the prediction from the pretrained model.Thanks.

**Comment by ZwwWayne** [comment]
Please refer to the [README.md](https://github.com/ZwwWayne/mmMOT/blob/master/README.md), we use the command as below:
```shell
python -u eval_seq.py --config ${work_path}/config.yaml \
--load-path=${work_path}/${model} \
--result-path=${work_path}/results \
--result_sha=eval
```
