### ISSUE TITLE
the detection result of  pedestrian of the PointPiller model in PKL format

### ISSUE THREAD

**Issue by yang0206** [ZwwWayne/mmMOT#31]
Hello!Thank you for your great code！I want to study pedestrian tracking. Could you please give me the detection result of  pedestrian of the PointPiller model in PKL format ?Thank you. Good luck with your work!

**Comment by ZwwWayne** [comment]
Since we do not study pedestrian tracking in the work, so we do not release pedestrian detection results in the work. You could use the released SECOND/PointPillars model to perform inference by yourself.

**Comment by yang0206** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZwwWayne/mmMOT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 晚上10:50
收件人:&nbsp;"ZwwWayne/mmMOT"<mmMOT@noreply.github.com&gt;;
抄送:&nbsp;"妮妮"<771379659@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZwwWayne/mmMOT] the detection result of  pedestrian of the PointPiller model in PKL format (#31)





 
Since we do not study pedestrian tracking in the work, so we do not release pedestrian detection results in the work. You could use the released SECOND/PointPillars model to perform inference by yourself.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

您好，不好意思这么晚打扰您，首先很感谢您的回信！我想请问一下，因为我这边检测的结果是.txt格式的文件，您那有.txt文件转为PKL文件的代码吗？我想参考学习一下。如果没有代码，您方便大概告诉我转换的思路吗？万分感谢！
