### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by baoxinchen** [ZwwWayne/mmMOT#6]
Hi @ZwwWayne,

Do you have the demo code to generate some graphical results? like those images in Figure 5 in your paper.

**Comment by ZwwWayne** [comment]
You can use `https://github.com/ZwwWayne/mmMOT/blob/master/utils/kitti_util.py` adopted from this [repo](https://github.com/kuixu/kitti_object_vis).

**Comment by llllliu1** [comment]
> Hi @ZwwWayne,
> 
> Do you have the demo code to generate some graphical results? like those images in Figure 5 in your paper.

@baoxinchen hey,did u save this problem?Or do you have a demo code to solve the visualization problem?thank you~
