### ISSUE TITLE
Pretrain Model and detection results

### ISSUE THREAD

**Issue by yinhai86924** [ZwwWayne/mmMOT#9]
> Hello,  Do you have any detection results of second 1.6  used for your tracking algorithm, I need to install second 1.6?

**Comment by yinhai86924** [comment]
> Hello,  Do you have any detection results for second 1.6 for your tracking algorithm, I need to install second 1.6?

**Comment by ZwwWayne** [comment]
Yes, you need to install SECOND1.6 first.

**Comment by simaker** [comment]
i've tried it, it will not work since the output format has changed from SECOND 1.5.1 to 1.6. Use 1.5.1
